// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  checkDatabaseConnectionApiV1CheckDbConnectionGet,
  createTodoApiV1TodosPost,
  createUserApiV1UsersPost,
  deleteTodoApiV1TodosIdDelete,
  deleteUserApiV1UsersIdDelete,
  getCurrentUserApiV1LoginCurrentUserGet,
  getCustomWelcomeMessageApiV1UserNameGet,
  getEnvSettingsApiV1GetEnvironmentGet,
  getWelcomeMessageApiV1Get,
  healthHealthGet,
  loginAccessTokenApiV1LoginAccessTokenPost,
  metricsMetricsGet,
  type Options,
  readAdminDashboardStatsApiV1AdminDashboardStatsGet,
  readAllActivitiesApiV1ActivitiesGet,
  readDashboardStatsApiV1DashboardStatsGet,
  readMyActivitiesApiV1ActivitiesMeGet,
  readPasswordHistoryApiV1UsersMePasswordHistoryGet,
  readSecureApiV1LoginSecureDataGet,
  readSystemLogsApiV1AdminDashboardLogsGet,
  readTodoByIdApiV1TodosIdGet,
  readTodosApiV1TodosGet,
  readUserByEmailApiV1UsersByEmailEmailGet,
  readUserByIdApiV1UsersByIdIdGet,
  readUsersApiV1UsersGet,
  recoverPasswordApiV1LoginPasswordRecoveryEmailPost,
  registerUserApiV1LoginSignupPost,
  testEmailTestEmailPost,
  triggerErrorApiV1AdminDashboardErrorTestGet,
  updatePasswordApiV1UsersPasswordPatch,
  updateTodoApiV1TodosIdPatch,
  updateUserApiV1UsersIdPatch,
} from "../sdk.gen";
import type {
  CheckDatabaseConnectionApiV1CheckDbConnectionGetData,
  CheckDatabaseConnectionApiV1CheckDbConnectionGetError,
  CheckDatabaseConnectionApiV1CheckDbConnectionGetResponse,
  CreateTodoApiV1TodosPostData,
  CreateTodoApiV1TodosPostError,
  CreateTodoApiV1TodosPostResponse,
  CreateUserApiV1UsersPostData,
  CreateUserApiV1UsersPostError,
  CreateUserApiV1UsersPostResponse,
  DeleteTodoApiV1TodosIdDeleteData,
  DeleteTodoApiV1TodosIdDeleteError,
  DeleteTodoApiV1TodosIdDeleteResponse,
  DeleteUserApiV1UsersIdDeleteData,
  DeleteUserApiV1UsersIdDeleteError,
  DeleteUserApiV1UsersIdDeleteResponse,
  GetCurrentUserApiV1LoginCurrentUserGetData,
  GetCurrentUserApiV1LoginCurrentUserGetError,
  GetCurrentUserApiV1LoginCurrentUserGetResponse,
  GetCustomWelcomeMessageApiV1UserNameGetData,
  GetCustomWelcomeMessageApiV1UserNameGetError,
  GetCustomWelcomeMessageApiV1UserNameGetResponse,
  GetEnvSettingsApiV1GetEnvironmentGetData,
  GetEnvSettingsApiV1GetEnvironmentGetError,
  GetEnvSettingsApiV1GetEnvironmentGetResponse,
  GetWelcomeMessageApiV1GetData,
  GetWelcomeMessageApiV1GetError,
  GetWelcomeMessageApiV1GetResponse,
  HealthHealthGetData,
  HealthHealthGetError,
  HealthHealthGetResponse,
  LoginAccessTokenApiV1LoginAccessTokenPostData,
  LoginAccessTokenApiV1LoginAccessTokenPostError,
  LoginAccessTokenApiV1LoginAccessTokenPostResponse,
  MetricsMetricsGetData,
  MetricsMetricsGetError,
  ReadAdminDashboardStatsApiV1AdminDashboardStatsGetData,
  ReadAdminDashboardStatsApiV1AdminDashboardStatsGetError,
  ReadAdminDashboardStatsApiV1AdminDashboardStatsGetResponse,
  ReadAllActivitiesApiV1ActivitiesGetData,
  ReadAllActivitiesApiV1ActivitiesGetError,
  ReadAllActivitiesApiV1ActivitiesGetResponse,
  ReadDashboardStatsApiV1DashboardStatsGetData,
  ReadDashboardStatsApiV1DashboardStatsGetError,
  ReadDashboardStatsApiV1DashboardStatsGetResponse,
  ReadMyActivitiesApiV1ActivitiesMeGetData,
  ReadMyActivitiesApiV1ActivitiesMeGetError,
  ReadMyActivitiesApiV1ActivitiesMeGetResponse,
  ReadPasswordHistoryApiV1UsersMePasswordHistoryGetData,
  ReadPasswordHistoryApiV1UsersMePasswordHistoryGetError,
  ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponse,
  ReadSecureApiV1LoginSecureDataGetData,
  ReadSecureApiV1LoginSecureDataGetError,
  ReadSecureApiV1LoginSecureDataGetResponse,
  ReadSystemLogsApiV1AdminDashboardLogsGetData,
  ReadSystemLogsApiV1AdminDashboardLogsGetError,
  ReadSystemLogsApiV1AdminDashboardLogsGetResponse,
  ReadTodoByIdApiV1TodosIdGetData,
  ReadTodoByIdApiV1TodosIdGetError,
  ReadTodoByIdApiV1TodosIdGetResponse,
  ReadTodosApiV1TodosGetData,
  ReadTodosApiV1TodosGetError,
  ReadTodosApiV1TodosGetResponse,
  ReadUserByEmailApiV1UsersByEmailEmailGetData,
  ReadUserByEmailApiV1UsersByEmailEmailGetError,
  ReadUserByEmailApiV1UsersByEmailEmailGetResponse,
  ReadUserByIdApiV1UsersByIdIdGetData,
  ReadUserByIdApiV1UsersByIdIdGetError,
  ReadUserByIdApiV1UsersByIdIdGetResponse,
  ReadUsersApiV1UsersGetData,
  ReadUsersApiV1UsersGetError,
  ReadUsersApiV1UsersGetResponse,
  RecoverPasswordApiV1LoginPasswordRecoveryEmailPostData,
  RecoverPasswordApiV1LoginPasswordRecoveryEmailPostError,
  RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponse,
  RegisterUserApiV1LoginSignupPostData,
  RegisterUserApiV1LoginSignupPostError,
  RegisterUserApiV1LoginSignupPostResponse,
  TestEmailTestEmailPostData,
  TestEmailTestEmailPostError,
  TestEmailTestEmailPostResponse,
  TriggerErrorApiV1AdminDashboardErrorTestGetData,
  TriggerErrorApiV1AdminDashboardErrorTestGetError,
  UpdatePasswordApiV1UsersPasswordPatchData,
  UpdatePasswordApiV1UsersPasswordPatchError,
  UpdatePasswordApiV1UsersPasswordPatchResponse,
  UpdateTodoApiV1TodosIdPatchData,
  UpdateTodoApiV1TodosIdPatchError,
  UpdateTodoApiV1TodosIdPatchResponse,
  UpdateUserApiV1UsersIdPatchData,
  UpdateUserApiV1UsersIdPatchError,
  UpdateUserApiV1UsersIdPatchResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const metricsMetricsGetQueryKey = (
  options?: Options<MetricsMetricsGetData>,
) => createQueryKey("metricsMetricsGet", options);

/**
 * Metrics
 *
 * Endpoint that serves Prometheus metrics.
 */
export const metricsMetricsGetOptions = (
  options?: Options<MetricsMetricsGetData>,
) =>
  queryOptions<
    unknown,
    MetricsMetricsGetError,
    unknown,
    ReturnType<typeof metricsMetricsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await metricsMetricsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: metricsMetricsGetQueryKey(options),
  });

export const checkDatabaseConnectionApiV1CheckDbConnectionGetQueryKey = (
  options?: Options<CheckDatabaseConnectionApiV1CheckDbConnectionGetData>,
) =>
  createQueryKey("checkDatabaseConnectionApiV1CheckDbConnectionGet", options);

/**
 * Check Database Connection
 */
export const checkDatabaseConnectionApiV1CheckDbConnectionGetOptions = (
  options?: Options<CheckDatabaseConnectionApiV1CheckDbConnectionGetData>,
) =>
  queryOptions<
    CheckDatabaseConnectionApiV1CheckDbConnectionGetResponse,
    CheckDatabaseConnectionApiV1CheckDbConnectionGetError,
    CheckDatabaseConnectionApiV1CheckDbConnectionGetResponse,
    ReturnType<typeof checkDatabaseConnectionApiV1CheckDbConnectionGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await checkDatabaseConnectionApiV1CheckDbConnectionGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: checkDatabaseConnectionApiV1CheckDbConnectionGetQueryKey(options),
  });

export const getEnvSettingsApiV1GetEnvironmentGetQueryKey = (
  options?: Options<GetEnvSettingsApiV1GetEnvironmentGetData>,
) => createQueryKey("getEnvSettingsApiV1GetEnvironmentGet", options);

/**
 * Get Env Settings
 */
export const getEnvSettingsApiV1GetEnvironmentGetOptions = (
  options?: Options<GetEnvSettingsApiV1GetEnvironmentGetData>,
) =>
  queryOptions<
    GetEnvSettingsApiV1GetEnvironmentGetResponse,
    GetEnvSettingsApiV1GetEnvironmentGetError,
    GetEnvSettingsApiV1GetEnvironmentGetResponse,
    ReturnType<typeof getEnvSettingsApiV1GetEnvironmentGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEnvSettingsApiV1GetEnvironmentGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEnvSettingsApiV1GetEnvironmentGetQueryKey(options),
  });

export const getCustomWelcomeMessageApiV1UserNameGetQueryKey = (
  options: Options<GetCustomWelcomeMessageApiV1UserNameGetData>,
) => createQueryKey("getCustomWelcomeMessageApiV1UserNameGet", options);

/**
 * Get Custom Welcome Message
 */
export const getCustomWelcomeMessageApiV1UserNameGetOptions = (
  options: Options<GetCustomWelcomeMessageApiV1UserNameGetData>,
) =>
  queryOptions<
    GetCustomWelcomeMessageApiV1UserNameGetResponse,
    GetCustomWelcomeMessageApiV1UserNameGetError,
    GetCustomWelcomeMessageApiV1UserNameGetResponse,
    ReturnType<typeof getCustomWelcomeMessageApiV1UserNameGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCustomWelcomeMessageApiV1UserNameGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCustomWelcomeMessageApiV1UserNameGetQueryKey(options),
  });

export const getWelcomeMessageApiV1GetQueryKey = (
  options?: Options<GetWelcomeMessageApiV1GetData>,
) => createQueryKey("getWelcomeMessageApiV1Get", options);

/**
 * Get Welcome Message
 */
export const getWelcomeMessageApiV1GetOptions = (
  options?: Options<GetWelcomeMessageApiV1GetData>,
) =>
  queryOptions<
    GetWelcomeMessageApiV1GetResponse,
    GetWelcomeMessageApiV1GetError,
    GetWelcomeMessageApiV1GetResponse,
    ReturnType<typeof getWelcomeMessageApiV1GetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWelcomeMessageApiV1Get({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWelcomeMessageApiV1GetQueryKey(options),
  });

export const readUsersApiV1UsersGetQueryKey = (
  options?: Options<ReadUsersApiV1UsersGetData>,
) => createQueryKey("readUsersApiV1UsersGet", options);

/**
 * Read Users
 */
export const readUsersApiV1UsersGetOptions = (
  options?: Options<ReadUsersApiV1UsersGetData>,
) =>
  queryOptions<
    ReadUsersApiV1UsersGetResponse,
    ReadUsersApiV1UsersGetError,
    ReadUsersApiV1UsersGetResponse,
    ReturnType<typeof readUsersApiV1UsersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readUsersApiV1UsersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readUsersApiV1UsersGetQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const readUsersApiV1UsersGetInfiniteQueryKey = (
  options?: Options<ReadUsersApiV1UsersGetData>,
): QueryKey<Options<ReadUsersApiV1UsersGetData>> =>
  createQueryKey("readUsersApiV1UsersGet", options, true);

/**
 * Read Users
 */
export const readUsersApiV1UsersGetInfiniteOptions = (
  options?: Options<ReadUsersApiV1UsersGetData>,
) =>
  infiniteQueryOptions<
    ReadUsersApiV1UsersGetResponse,
    ReadUsersApiV1UsersGetError,
    InfiniteData<ReadUsersApiV1UsersGetResponse>,
    QueryKey<Options<ReadUsersApiV1UsersGetData>>,
    | number
    | Pick<
        QueryKey<Options<ReadUsersApiV1UsersGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ReadUsersApiV1UsersGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readUsersApiV1UsersGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: readUsersApiV1UsersGetInfiniteQueryKey(options),
    },
  );

/**
 * Create User
 */
export const createUserApiV1UsersPostMutation = (
  options?: Partial<Options<CreateUserApiV1UsersPostData>>,
): UseMutationOptions<
  CreateUserApiV1UsersPostResponse,
  CreateUserApiV1UsersPostError,
  Options<CreateUserApiV1UsersPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserApiV1UsersPostResponse,
    CreateUserApiV1UsersPostError,
    Options<CreateUserApiV1UsersPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUserApiV1UsersPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const readUserByIdApiV1UsersByIdIdGetQueryKey = (
  options: Options<ReadUserByIdApiV1UsersByIdIdGetData>,
) => createQueryKey("readUserByIdApiV1UsersByIdIdGet", options);

/**
 * Read User By Id
 */
export const readUserByIdApiV1UsersByIdIdGetOptions = (
  options: Options<ReadUserByIdApiV1UsersByIdIdGetData>,
) =>
  queryOptions<
    ReadUserByIdApiV1UsersByIdIdGetResponse,
    ReadUserByIdApiV1UsersByIdIdGetError,
    ReadUserByIdApiV1UsersByIdIdGetResponse,
    ReturnType<typeof readUserByIdApiV1UsersByIdIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readUserByIdApiV1UsersByIdIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readUserByIdApiV1UsersByIdIdGetQueryKey(options),
  });

export const readUserByEmailApiV1UsersByEmailEmailGetQueryKey = (
  options: Options<ReadUserByEmailApiV1UsersByEmailEmailGetData>,
) => createQueryKey("readUserByEmailApiV1UsersByEmailEmailGet", options);

/**
 * Read User By Email
 */
export const readUserByEmailApiV1UsersByEmailEmailGetOptions = (
  options: Options<ReadUserByEmailApiV1UsersByEmailEmailGetData>,
) =>
  queryOptions<
    ReadUserByEmailApiV1UsersByEmailEmailGetResponse,
    ReadUserByEmailApiV1UsersByEmailEmailGetError,
    ReadUserByEmailApiV1UsersByEmailEmailGetResponse,
    ReturnType<typeof readUserByEmailApiV1UsersByEmailEmailGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readUserByEmailApiV1UsersByEmailEmailGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readUserByEmailApiV1UsersByEmailEmailGetQueryKey(options),
  });

export const readPasswordHistoryApiV1UsersMePasswordHistoryGetQueryKey = (
  options?: Options<ReadPasswordHistoryApiV1UsersMePasswordHistoryGetData>,
) =>
  createQueryKey("readPasswordHistoryApiV1UsersMePasswordHistoryGet", options);

/**
 * Read Password History
 *
 * Retrieve the last 5 password changes for the authenticated user.
 */
export const readPasswordHistoryApiV1UsersMePasswordHistoryGetOptions = (
  options?: Options<ReadPasswordHistoryApiV1UsersMePasswordHistoryGetData>,
) =>
  queryOptions<
    ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponse,
    ReadPasswordHistoryApiV1UsersMePasswordHistoryGetError,
    ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponse,
    ReturnType<typeof readPasswordHistoryApiV1UsersMePasswordHistoryGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readPasswordHistoryApiV1UsersMePasswordHistoryGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey:
      readPasswordHistoryApiV1UsersMePasswordHistoryGetQueryKey(options),
  });

/**
 * Update Password
 */
export const updatePasswordApiV1UsersPasswordPatchMutation = (
  options?: Partial<Options<UpdatePasswordApiV1UsersPasswordPatchData>>,
): UseMutationOptions<
  UpdatePasswordApiV1UsersPasswordPatchResponse,
  UpdatePasswordApiV1UsersPasswordPatchError,
  Options<UpdatePasswordApiV1UsersPasswordPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdatePasswordApiV1UsersPasswordPatchResponse,
    UpdatePasswordApiV1UsersPasswordPatchError,
    Options<UpdatePasswordApiV1UsersPasswordPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updatePasswordApiV1UsersPasswordPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete User
 */
export const deleteUserApiV1UsersIdDeleteMutation = (
  options?: Partial<Options<DeleteUserApiV1UsersIdDeleteData>>,
): UseMutationOptions<
  DeleteUserApiV1UsersIdDeleteResponse,
  DeleteUserApiV1UsersIdDeleteError,
  Options<DeleteUserApiV1UsersIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteUserApiV1UsersIdDeleteResponse,
    DeleteUserApiV1UsersIdDeleteError,
    Options<DeleteUserApiV1UsersIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUserApiV1UsersIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update User
 */
export const updateUserApiV1UsersIdPatchMutation = (
  options?: Partial<Options<UpdateUserApiV1UsersIdPatchData>>,
): UseMutationOptions<
  UpdateUserApiV1UsersIdPatchResponse,
  UpdateUserApiV1UsersIdPatchError,
  Options<UpdateUserApiV1UsersIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUserApiV1UsersIdPatchResponse,
    UpdateUserApiV1UsersIdPatchError,
    Options<UpdateUserApiV1UsersIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUserApiV1UsersIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const readTodosApiV1TodosGetQueryKey = (
  options?: Options<ReadTodosApiV1TodosGetData>,
) => createQueryKey("readTodosApiV1TodosGet", options);

/**
 * Read Todos
 */
export const readTodosApiV1TodosGetOptions = (
  options?: Options<ReadTodosApiV1TodosGetData>,
) =>
  queryOptions<
    ReadTodosApiV1TodosGetResponse,
    ReadTodosApiV1TodosGetError,
    ReadTodosApiV1TodosGetResponse,
    ReturnType<typeof readTodosApiV1TodosGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readTodosApiV1TodosGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readTodosApiV1TodosGetQueryKey(options),
  });

/**
 * Create Todo
 */
export const createTodoApiV1TodosPostMutation = (
  options?: Partial<Options<CreateTodoApiV1TodosPostData>>,
): UseMutationOptions<
  CreateTodoApiV1TodosPostResponse,
  CreateTodoApiV1TodosPostError,
  Options<CreateTodoApiV1TodosPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTodoApiV1TodosPostResponse,
    CreateTodoApiV1TodosPostError,
    Options<CreateTodoApiV1TodosPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTodoApiV1TodosPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Todo
 */
export const deleteTodoApiV1TodosIdDeleteMutation = (
  options?: Partial<Options<DeleteTodoApiV1TodosIdDeleteData>>,
): UseMutationOptions<
  DeleteTodoApiV1TodosIdDeleteResponse,
  DeleteTodoApiV1TodosIdDeleteError,
  Options<DeleteTodoApiV1TodosIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTodoApiV1TodosIdDeleteResponse,
    DeleteTodoApiV1TodosIdDeleteError,
    Options<DeleteTodoApiV1TodosIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTodoApiV1TodosIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const readTodoByIdApiV1TodosIdGetQueryKey = (
  options: Options<ReadTodoByIdApiV1TodosIdGetData>,
) => createQueryKey("readTodoByIdApiV1TodosIdGet", options);

/**
 * Read Todo By Id
 */
export const readTodoByIdApiV1TodosIdGetOptions = (
  options: Options<ReadTodoByIdApiV1TodosIdGetData>,
) =>
  queryOptions<
    ReadTodoByIdApiV1TodosIdGetResponse,
    ReadTodoByIdApiV1TodosIdGetError,
    ReadTodoByIdApiV1TodosIdGetResponse,
    ReturnType<typeof readTodoByIdApiV1TodosIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readTodoByIdApiV1TodosIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readTodoByIdApiV1TodosIdGetQueryKey(options),
  });

/**
 * Update Todo
 */
export const updateTodoApiV1TodosIdPatchMutation = (
  options?: Partial<Options<UpdateTodoApiV1TodosIdPatchData>>,
): UseMutationOptions<
  UpdateTodoApiV1TodosIdPatchResponse,
  UpdateTodoApiV1TodosIdPatchError,
  Options<UpdateTodoApiV1TodosIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateTodoApiV1TodosIdPatchResponse,
    UpdateTodoApiV1TodosIdPatchError,
    Options<UpdateTodoApiV1TodosIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateTodoApiV1TodosIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginAccessTokenApiV1LoginAccessTokenPostMutation = (
  options?: Partial<Options<LoginAccessTokenApiV1LoginAccessTokenPostData>>,
): UseMutationOptions<
  LoginAccessTokenApiV1LoginAccessTokenPostResponse,
  LoginAccessTokenApiV1LoginAccessTokenPostError,
  Options<LoginAccessTokenApiV1LoginAccessTokenPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginAccessTokenApiV1LoginAccessTokenPostResponse,
    LoginAccessTokenApiV1LoginAccessTokenPostError,
    Options<LoginAccessTokenApiV1LoginAccessTokenPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await loginAccessTokenApiV1LoginAccessTokenPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const readSecureApiV1LoginSecureDataGetQueryKey = (
  options?: Options<ReadSecureApiV1LoginSecureDataGetData>,
) => createQueryKey("readSecureApiV1LoginSecureDataGet", options);

/**
 * Read Secure
 */
export const readSecureApiV1LoginSecureDataGetOptions = (
  options?: Options<ReadSecureApiV1LoginSecureDataGetData>,
) =>
  queryOptions<
    ReadSecureApiV1LoginSecureDataGetResponse,
    ReadSecureApiV1LoginSecureDataGetError,
    ReadSecureApiV1LoginSecureDataGetResponse,
    ReturnType<typeof readSecureApiV1LoginSecureDataGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readSecureApiV1LoginSecureDataGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readSecureApiV1LoginSecureDataGetQueryKey(options),
  });

export const getCurrentUserApiV1LoginCurrentUserGetQueryKey = (
  options?: Options<GetCurrentUserApiV1LoginCurrentUserGetData>,
) => createQueryKey("getCurrentUserApiV1LoginCurrentUserGet", options);

/**
 * Get Current User
 */
export const getCurrentUserApiV1LoginCurrentUserGetOptions = (
  options?: Options<GetCurrentUserApiV1LoginCurrentUserGetData>,
) =>
  queryOptions<
    GetCurrentUserApiV1LoginCurrentUserGetResponse,
    GetCurrentUserApiV1LoginCurrentUserGetError,
    GetCurrentUserApiV1LoginCurrentUserGetResponse,
    ReturnType<typeof getCurrentUserApiV1LoginCurrentUserGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentUserApiV1LoginCurrentUserGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCurrentUserApiV1LoginCurrentUserGetQueryKey(options),
  });

/**
 * Register User
 *
 * Public signup endpoint for new users.
 */
export const registerUserApiV1LoginSignupPostMutation = (
  options?: Partial<Options<RegisterUserApiV1LoginSignupPostData>>,
): UseMutationOptions<
  RegisterUserApiV1LoginSignupPostResponse,
  RegisterUserApiV1LoginSignupPostError,
  Options<RegisterUserApiV1LoginSignupPostData>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterUserApiV1LoginSignupPostResponse,
    RegisterUserApiV1LoginSignupPostError,
    Options<RegisterUserApiV1LoginSignupPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await registerUserApiV1LoginSignupPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Recover Password
 */
export const recoverPasswordApiV1LoginPasswordRecoveryEmailPostMutation = (
  options?: Partial<
    Options<RecoverPasswordApiV1LoginPasswordRecoveryEmailPostData>
  >,
): UseMutationOptions<
  RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponse,
  RecoverPasswordApiV1LoginPasswordRecoveryEmailPostError,
  Options<RecoverPasswordApiV1LoginPasswordRecoveryEmailPostData>
> => {
  const mutationOptions: UseMutationOptions<
    RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponse,
    RecoverPasswordApiV1LoginPasswordRecoveryEmailPostError,
    Options<RecoverPasswordApiV1LoginPasswordRecoveryEmailPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await recoverPasswordApiV1LoginPasswordRecoveryEmailPost(
        {
          ...options,
          ...fnOptions,
          throwOnError: true,
        },
      );
      return data;
    },
  };
  return mutationOptions;
};

export const readMyActivitiesApiV1ActivitiesMeGetQueryKey = (
  options?: Options<ReadMyActivitiesApiV1ActivitiesMeGetData>,
) => createQueryKey("readMyActivitiesApiV1ActivitiesMeGet", options);

/**
 * Read My Activities
 *
 * Retrieve the last 20 activities for the authenticated user.
 */
export const readMyActivitiesApiV1ActivitiesMeGetOptions = (
  options?: Options<ReadMyActivitiesApiV1ActivitiesMeGetData>,
) =>
  queryOptions<
    ReadMyActivitiesApiV1ActivitiesMeGetResponse,
    ReadMyActivitiesApiV1ActivitiesMeGetError,
    ReadMyActivitiesApiV1ActivitiesMeGetResponse,
    ReturnType<typeof readMyActivitiesApiV1ActivitiesMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readMyActivitiesApiV1ActivitiesMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readMyActivitiesApiV1ActivitiesMeGetQueryKey(options),
  });

export const readAllActivitiesApiV1ActivitiesGetQueryKey = (
  options?: Options<ReadAllActivitiesApiV1ActivitiesGetData>,
) => createQueryKey("readAllActivitiesApiV1ActivitiesGet", options);

/**
 * Read All Activities
 *
 * Retrieve all system-wide activities (SUPER users only).
 */
export const readAllActivitiesApiV1ActivitiesGetOptions = (
  options?: Options<ReadAllActivitiesApiV1ActivitiesGetData>,
) =>
  queryOptions<
    ReadAllActivitiesApiV1ActivitiesGetResponse,
    ReadAllActivitiesApiV1ActivitiesGetError,
    ReadAllActivitiesApiV1ActivitiesGetResponse,
    ReturnType<typeof readAllActivitiesApiV1ActivitiesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readAllActivitiesApiV1ActivitiesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readAllActivitiesApiV1ActivitiesGetQueryKey(options),
  });

export const readAllActivitiesApiV1ActivitiesGetInfiniteQueryKey = (
  options?: Options<ReadAllActivitiesApiV1ActivitiesGetData>,
): QueryKey<Options<ReadAllActivitiesApiV1ActivitiesGetData>> =>
  createQueryKey("readAllActivitiesApiV1ActivitiesGet", options, true);

/**
 * Read All Activities
 *
 * Retrieve all system-wide activities (SUPER users only).
 */
export const readAllActivitiesApiV1ActivitiesGetInfiniteOptions = (
  options?: Options<ReadAllActivitiesApiV1ActivitiesGetData>,
) =>
  infiniteQueryOptions<
    ReadAllActivitiesApiV1ActivitiesGetResponse,
    ReadAllActivitiesApiV1ActivitiesGetError,
    InfiniteData<ReadAllActivitiesApiV1ActivitiesGetResponse>,
    QueryKey<Options<ReadAllActivitiesApiV1ActivitiesGetData>>,
    | number
    | Pick<
        QueryKey<Options<ReadAllActivitiesApiV1ActivitiesGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ReadAllActivitiesApiV1ActivitiesGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readAllActivitiesApiV1ActivitiesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: readAllActivitiesApiV1ActivitiesGetInfiniteQueryKey(options),
    },
  );

export const readDashboardStatsApiV1DashboardStatsGetQueryKey = (
  options?: Options<ReadDashboardStatsApiV1DashboardStatsGetData>,
) => createQueryKey("readDashboardStatsApiV1DashboardStatsGet", options);

/**
 * Read Dashboard Stats
 *
 * Retrieve comprehensive system and application metrics (SUPER users only).
 */
export const readDashboardStatsApiV1DashboardStatsGetOptions = (
  options?: Options<ReadDashboardStatsApiV1DashboardStatsGetData>,
) =>
  queryOptions<
    ReadDashboardStatsApiV1DashboardStatsGetResponse,
    ReadDashboardStatsApiV1DashboardStatsGetError,
    ReadDashboardStatsApiV1DashboardStatsGetResponse,
    ReturnType<typeof readDashboardStatsApiV1DashboardStatsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readDashboardStatsApiV1DashboardStatsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readDashboardStatsApiV1DashboardStatsGetQueryKey(options),
  });

export const readAdminDashboardStatsApiV1AdminDashboardStatsGetQueryKey = (
  options?: Options<ReadAdminDashboardStatsApiV1AdminDashboardStatsGetData>,
) =>
  createQueryKey("readAdminDashboardStatsApiV1AdminDashboardStatsGet", options);

/**
 * Read Admin Dashboard Stats
 *
 * Retrieve user activity metrics and trends (SUPER and ADMIN users only).
 * Filters out activities from non-regular users.
 */
export const readAdminDashboardStatsApiV1AdminDashboardStatsGetOptions = (
  options?: Options<ReadAdminDashboardStatsApiV1AdminDashboardStatsGetData>,
) =>
  queryOptions<
    ReadAdminDashboardStatsApiV1AdminDashboardStatsGetResponse,
    ReadAdminDashboardStatsApiV1AdminDashboardStatsGetError,
    ReadAdminDashboardStatsApiV1AdminDashboardStatsGetResponse,
    ReturnType<
      typeof readAdminDashboardStatsApiV1AdminDashboardStatsGetQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readAdminDashboardStatsApiV1AdminDashboardStatsGet(
        {
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        },
      );
      return data;
    },
    queryKey:
      readAdminDashboardStatsApiV1AdminDashboardStatsGetQueryKey(options),
  });

export const readSystemLogsApiV1AdminDashboardLogsGetQueryKey = (
  options?: Options<ReadSystemLogsApiV1AdminDashboardLogsGetData>,
) => createQueryKey("readSystemLogsApiV1AdminDashboardLogsGet", options);

/**
 * Read System Logs
 *
 * Retrieve recent system error logs (SUPER users only).
 */
export const readSystemLogsApiV1AdminDashboardLogsGetOptions = (
  options?: Options<ReadSystemLogsApiV1AdminDashboardLogsGetData>,
) =>
  queryOptions<
    ReadSystemLogsApiV1AdminDashboardLogsGetResponse,
    ReadSystemLogsApiV1AdminDashboardLogsGetError,
    ReadSystemLogsApiV1AdminDashboardLogsGetResponse,
    ReturnType<typeof readSystemLogsApiV1AdminDashboardLogsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readSystemLogsApiV1AdminDashboardLogsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readSystemLogsApiV1AdminDashboardLogsGetQueryKey(options),
  });

export const triggerErrorApiV1AdminDashboardErrorTestGetQueryKey = (
  options?: Options<TriggerErrorApiV1AdminDashboardErrorTestGetData>,
) => createQueryKey("triggerErrorApiV1AdminDashboardErrorTestGet", options);

/**
 * Trigger Error
 *
 * Deliberately trigger an error to test the global exception handler (SUPER users only).
 */
export const triggerErrorApiV1AdminDashboardErrorTestGetOptions = (
  options?: Options<TriggerErrorApiV1AdminDashboardErrorTestGetData>,
) =>
  queryOptions<
    unknown,
    TriggerErrorApiV1AdminDashboardErrorTestGetError,
    unknown,
    ReturnType<typeof triggerErrorApiV1AdminDashboardErrorTestGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await triggerErrorApiV1AdminDashboardErrorTestGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: triggerErrorApiV1AdminDashboardErrorTestGetQueryKey(options),
  });

export const healthHealthGetQueryKey = (
  options?: Options<HealthHealthGetData>,
) => createQueryKey("healthHealthGet", options);

/**
 * Health
 */
export const healthHealthGetOptions = (
  options?: Options<HealthHealthGetData>,
) =>
  queryOptions<
    HealthHealthGetResponse,
    HealthHealthGetError,
    HealthHealthGetResponse,
    ReturnType<typeof healthHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthHealthGetQueryKey(options),
  });

/**
 * Test Email
 */
export const testEmailTestEmailPostMutation = (
  options?: Partial<Options<TestEmailTestEmailPostData>>,
): UseMutationOptions<
  TestEmailTestEmailPostResponse,
  TestEmailTestEmailPostError,
  Options<TestEmailTestEmailPostData>
> => {
  const mutationOptions: UseMutationOptions<
    TestEmailTestEmailPostResponse,
    TestEmailTestEmailPostError,
    Options<TestEmailTestEmailPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await testEmailTestEmailPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
