// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_login_access_token_api_v1_login_access_token_post
 */
export type BodyLoginAccessTokenApiV1LoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * ToDoListCreate
 */
export type ToDoListCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    status?: ToDoStatus;
    /**
     * Due Date Time
     */
    due_date_time?: string | null;
    priority?: ToDoPriority;
};

/**
 * ToDoListPublic
 */
export type ToDoListPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    status?: ToDoStatus;
    /**
     * Due Date Time
     */
    due_date_time?: string | null;
    priority?: ToDoPriority;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ToDoListUpdate
 */
export type ToDoListUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    status?: ToDoStatus | null;
    /**
     * Due Date Time
     */
    due_date_time?: string | null;
    priority?: ToDoPriority | null;
};

/**
 * ToDoListsPublic
 */
export type ToDoListsPublic = {
    /**
     * Data
     */
    data: Array<ToDoListPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ToDoPriority
 */
export type ToDoPriority = 'high' | 'medium' | 'low';

/**
 * ToDoStatus
 */
export type ToDoStatus = 'pending' | 'in progress' | 'completed';

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    role?: UserRole;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    role?: UserRole;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRole
 */
export type UserRole = 'admin' | 'user' | 'guest';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    role?: UserRole | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/checkDBConnection';
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetResponses = {
    /**
     * Response Check Database Connection Api V1 Checkdbconnection Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetResponse = CheckDatabaseConnectionApiV1CheckDbConnectionGetResponses[keyof CheckDatabaseConnectionApiV1CheckDbConnectionGetResponses];

export type GetEnvSettingsApiV1GetEnvironmentGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/getEnvironment';
};

export type GetEnvSettingsApiV1GetEnvironmentGetResponses = {
    /**
     * Response Get Env Settings Api V1 Getenvironment Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetEnvSettingsApiV1GetEnvironmentGetResponse = GetEnvSettingsApiV1GetEnvironmentGetResponses[keyof GetEnvSettingsApiV1GetEnvironmentGetResponses];

export type GetCustomWelcomeMessageApiV1UserNameGetData = {
    body?: never;
    path: {
        /**
         * User Name
         */
        user_name: string;
    };
    query?: never;
    url: '/api/v1/{user_name}';
};

export type GetCustomWelcomeMessageApiV1UserNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCustomWelcomeMessageApiV1UserNameGetError = GetCustomWelcomeMessageApiV1UserNameGetErrors[keyof GetCustomWelcomeMessageApiV1UserNameGetErrors];

export type GetCustomWelcomeMessageApiV1UserNameGetResponses = {
    /**
     * Response Get Custom Welcome Message Api V1  User Name  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetCustomWelcomeMessageApiV1UserNameGetResponse = GetCustomWelcomeMessageApiV1UserNameGetResponses[keyof GetCustomWelcomeMessageApiV1UserNameGetResponses];

export type GetWelcomeMessageApiV1GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/';
};

export type GetWelcomeMessageApiV1GetResponses = {
    /**
     * Response Get Welcome Message Api V1  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetWelcomeMessageApiV1GetResponse = GetWelcomeMessageApiV1GetResponses[keyof GetWelcomeMessageApiV1GetResponses];

export type ReadUsersApiV1UsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type ReadUsersApiV1UsersGetResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type ReadUsersApiV1UsersGetResponse = ReadUsersApiV1UsersGetResponses[keyof ReadUsersApiV1UsersGetResponses];

export type CreateUserApiV1UsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserApiV1UsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError = CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserApiV1UsersPostResponse = CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type ReadUserByIdApiV1UsersByIdIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/byID/{id}';
};

export type ReadUserByIdApiV1UsersByIdIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdApiV1UsersByIdIdGetError = ReadUserByIdApiV1UsersByIdIdGetErrors[keyof ReadUserByIdApiV1UsersByIdIdGetErrors];

export type ReadUserByIdApiV1UsersByIdIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByIdApiV1UsersByIdIdGetResponse = ReadUserByIdApiV1UsersByIdIdGetResponses[keyof ReadUserByIdApiV1UsersByIdIdGetResponses];

export type ReadUserByEmailApiV1UsersByEmailEmailGetData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/users/byEmail/{email}';
};

export type ReadUserByEmailApiV1UsersByEmailEmailGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByEmailApiV1UsersByEmailEmailGetError = ReadUserByEmailApiV1UsersByEmailEmailGetErrors[keyof ReadUserByEmailApiV1UsersByEmailEmailGetErrors];

export type ReadUserByEmailApiV1UsersByEmailEmailGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByEmailApiV1UsersByEmailEmailGetResponse = ReadUserByEmailApiV1UsersByEmailEmailGetResponses[keyof ReadUserByEmailApiV1UsersByEmailEmailGetResponses];

export type UpdatePasswordApiV1UsersPasswordPatchData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/password';
};

export type UpdatePasswordApiV1UsersPasswordPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordApiV1UsersPasswordPatchError = UpdatePasswordApiV1UsersPasswordPatchErrors[keyof UpdatePasswordApiV1UsersPasswordPatchErrors];

export type UpdatePasswordApiV1UsersPasswordPatchResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UpdatePasswordApiV1UsersPasswordPatchResponse = UpdatePasswordApiV1UsersPasswordPatchResponses[keyof UpdatePasswordApiV1UsersPasswordPatchResponses];

export type DeleteUserApiV1UsersIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type DeleteUserApiV1UsersIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiV1UsersIdDeleteError = DeleteUserApiV1UsersIdDeleteErrors[keyof DeleteUserApiV1UsersIdDeleteErrors];

export type DeleteUserApiV1UsersIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserApiV1UsersIdDeleteResponse = DeleteUserApiV1UsersIdDeleteResponses[keyof DeleteUserApiV1UsersIdDeleteResponses];

export type UpdateUserApiV1UsersIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type UpdateUserApiV1UsersIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1UsersIdPatchError = UpdateUserApiV1UsersIdPatchErrors[keyof UpdateUserApiV1UsersIdPatchErrors];

export type UpdateUserApiV1UsersIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserApiV1UsersIdPatchResponse = UpdateUserApiV1UsersIdPatchResponses[keyof UpdateUserApiV1UsersIdPatchResponses];

export type ReadTodosApiV1TodosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/todos/';
};

export type ReadTodosApiV1TodosGetResponses = {
    /**
     * Successful Response
     */
    200: ToDoListsPublic;
};

export type ReadTodosApiV1TodosGetResponse = ReadTodosApiV1TodosGetResponses[keyof ReadTodosApiV1TodosGetResponses];

export type CreateTodoApiV1TodosPostData = {
    body: ToDoListCreate;
    path?: never;
    query?: never;
    url: '/api/v1/todos/';
};

export type CreateTodoApiV1TodosPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTodoApiV1TodosPostError = CreateTodoApiV1TodosPostErrors[keyof CreateTodoApiV1TodosPostErrors];

export type CreateTodoApiV1TodosPostResponses = {
    /**
     * Successful Response
     */
    200: ToDoListPublic;
};

export type CreateTodoApiV1TodosPostResponse = CreateTodoApiV1TodosPostResponses[keyof CreateTodoApiV1TodosPostResponses];

export type DeleteTodoApiV1TodosIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/todos/{id}';
};

export type DeleteTodoApiV1TodosIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTodoApiV1TodosIdDeleteError = DeleteTodoApiV1TodosIdDeleteErrors[keyof DeleteTodoApiV1TodosIdDeleteErrors];

export type DeleteTodoApiV1TodosIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteTodoApiV1TodosIdDeleteResponse = DeleteTodoApiV1TodosIdDeleteResponses[keyof DeleteTodoApiV1TodosIdDeleteResponses];

export type ReadTodoByIdApiV1TodosIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/todos/{id}';
};

export type ReadTodoByIdApiV1TodosIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTodoByIdApiV1TodosIdGetError = ReadTodoByIdApiV1TodosIdGetErrors[keyof ReadTodoByIdApiV1TodosIdGetErrors];

export type ReadTodoByIdApiV1TodosIdGetResponses = {
    /**
     * Successful Response
     */
    200: ToDoListPublic;
};

export type ReadTodoByIdApiV1TodosIdGetResponse = ReadTodoByIdApiV1TodosIdGetResponses[keyof ReadTodoByIdApiV1TodosIdGetResponses];

export type UpdateTodoApiV1TodosIdPatchData = {
    body: ToDoListUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/todos/{id}';
};

export type UpdateTodoApiV1TodosIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTodoApiV1TodosIdPatchError = UpdateTodoApiV1TodosIdPatchErrors[keyof UpdateTodoApiV1TodosIdPatchErrors];

export type UpdateTodoApiV1TodosIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ToDoListPublic;
};

export type UpdateTodoApiV1TodosIdPatchResponse = UpdateTodoApiV1TodosIdPatchResponses[keyof UpdateTodoApiV1TodosIdPatchResponses];

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    body: BodyLoginAccessTokenApiV1LoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenApiV1LoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostError = LoginAccessTokenApiV1LoginAccessTokenPostErrors[keyof LoginAccessTokenApiV1LoginAccessTokenPostErrors];

export type LoginAccessTokenApiV1LoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = LoginAccessTokenApiV1LoginAccessTokenPostResponses[keyof LoginAccessTokenApiV1LoginAccessTokenPostResponses];

export type ReadSecureApiV1LoginSecureDataGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/secure-data';
};

export type ReadSecureApiV1LoginSecureDataGetResponses = {
    /**
     * Response Read Secure Api V1 Login Secure Data Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadSecureApiV1LoginSecureDataGetResponse = ReadSecureApiV1LoginSecureDataGetResponses[keyof ReadSecureApiV1LoginSecureDataGetResponses];

export type GetCurrentUserApiV1LoginCurrentUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/current-user';
};

export type GetCurrentUserApiV1LoginCurrentUserGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetCurrentUserApiV1LoginCurrentUserGetResponse = GetCurrentUserApiV1LoginCurrentUserGetResponses[keyof GetCurrentUserApiV1LoginCurrentUserGetResponses];

export type RegisterUserApiV1LoginSignupPostData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/login/signup';
};

export type RegisterUserApiV1LoginSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserApiV1LoginSignupPostError = RegisterUserApiV1LoginSignupPostErrors[keyof RegisterUserApiV1LoginSignupPostErrors];

export type RegisterUserApiV1LoginSignupPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type RegisterUserApiV1LoginSignupPostResponse = RegisterUserApiV1LoginSignupPostResponses[keyof RegisterUserApiV1LoginSignupPostResponses];

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/login/password-recovery/{email}';
};

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostError = RecoverPasswordApiV1LoginPasswordRecoveryEmailPostErrors[keyof RecoverPasswordApiV1LoginPasswordRecoveryEmailPostErrors];

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponse = RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponses[keyof RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type TestEmailTestEmailPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/test-email/';
};

export type TestEmailTestEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestEmailTestEmailPostError = TestEmailTestEmailPostErrors[keyof TestEmailTestEmailPostErrors];

export type TestEmailTestEmailPostResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type TestEmailTestEmailPostResponse = TestEmailTestEmailPostResponses[keyof TestEmailTestEmailPostResponses];
