// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * ActivitySummary
 */
export type ActivitySummary = {
  /**
   * Total Hits
   */
  total_hits: number;
  /**
   * Success Rate
   */
  success_rate: number;
  /**
   * Failure Rate
   */
  failure_rate: number;
  /**
   * Top Endpoints
   */
  top_endpoints: Array<HotEndpoint>;
};

/**
 * AdminDashboardReport
 */
export type AdminDashboardReport = {
  /**
   * Total Regular Users
   */
  total_regular_users: number;
  /**
   * Total Activities 24H
   */
  total_activities_24h: number;
  /**
   * Daily Trends
   */
  daily_trends: Array<DailyActivity>;
  /**
   * Top Active Users
   */
  top_active_users: Array<UserActivityStat>;
};

/**
 * Body_login_access_token_api_v1_login_access_token_post
 */
export type BodyLoginAccessTokenApiV1LoginAccessTokenPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * DailyActivity
 */
export type DailyActivity = {
  /**
   * Date
   */
  date: string;
  /**
   * Count
   */
  count: number;
};

/**
 * DashboardReport
 */
export type DashboardReport = {
  server: ServerMetrics;
  users: UserStats;
  activity: ActivitySummary;
};

/**
 * ErrorDetail
 */
export type ErrorDetail = {
  /**
   * Detail
   *
   * A specific error message suitable for UI display
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HotEndpoint
 */
export type HotEndpoint = {
  /**
   * Path
   */
  path: string;
  /**
   * Method
   */
  method: string;
  /**
   * Count
   */
  count: number;
};

/**
 * Message
 */
export type Message = {
  /**
   * Message
   *
   * A human-readable success or status message
   */
  message: string;
};

/**
 * Page[UserActivityPublic]
 */
export type PageUserActivityPublic = {
  /**
   * Items
   */
  items: Array<UserActivityPublic>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};

/**
 * Page[UserPublic]
 */
export type PageUserPublic = {
  /**
   * Items
   */
  items: Array<UserPublic>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Size
   */
  size: number;
  /**
   * Pages
   */
  pages: number;
};

/**
 * PasswordHistoriesPublic
 */
export type PasswordHistoriesPublic = {
  /**
   * Data
   */
  data: Array<PasswordHistoryPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * PasswordHistoryPublic
 */
export type PasswordHistoryPublic = {
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * ServerMetrics
 */
export type ServerMetrics = {
  /**
   * Cpu Usage
   */
  cpu_usage: number;
  /**
   * Memory Usage
   */
  memory_usage: number;
  /**
   * Disk Usage
   */
  disk_usage: number;
  /**
   * Uptime Seconds
   */
  uptime_seconds: number;
};

/**
 * SystemLogPublic
 */
export type SystemLogPublic = {
  /**
   * Level
   */
  level: string;
  /**
   * Message
   */
  message: string;
  /**
   * Path
   */
  path?: string | null;
  /**
   * Method
   */
  method?: string | null;
  /**
   * Status Code
   */
  status_code?: number | null;
  /**
   * User Id
   */
  user_id?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Stack Trace
   */
  stack_trace?: string | null;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * SystemLogsPublic
 */
export type SystemLogsPublic = {
  /**
   * Data
   */
  data: Array<SystemLogPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * ToDoListCreate
 */
export type ToDoListCreate = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  status?: ToDoStatus;
  /**
   * Due Date Time
   */
  due_date_time?: string | null;
  priority?: ToDoPriority;
};

/**
 * ToDoListPublic
 */
export type ToDoListPublic = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  status?: ToDoStatus;
  /**
   * Due Date Time
   */
  due_date_time?: string | null;
  priority?: ToDoPriority;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * ToDoListUpdate
 */
export type ToDoListUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  status?: ToDoStatus | null;
  /**
   * Due Date Time
   */
  due_date_time?: string | null;
  priority?: ToDoPriority | null;
};

/**
 * ToDoListsPublic
 */
export type ToDoListsPublic = {
  /**
   * Data
   */
  data: Array<ToDoListPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * ToDoPriority
 */
export type ToDoPriority = "high" | "medium" | "low";

/**
 * ToDoStatus
 */
export type ToDoStatus = "pending" | "in progress" | "completed";

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
  /**
   * Current Password
   */
  current_password: string;
  /**
   * New Password
   */
  new_password: string;
};

/**
 * UserActivitiesPublic
 */
export type UserActivitiesPublic = {
  /**
   * Data
   */
  data: Array<UserActivityPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * UserActivityPublic
 */
export type UserActivityPublic = {
  /**
   * Method
   */
  method: string;
  /**
   * Path
   */
  path: string;
  /**
   * Status Code
   */
  status_code: number;
  /**
   * Ip Address
   */
  ip_address?: string | null;
  /**
   * User Agent
   */
  user_agent?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string | null;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * UserActivityStat
 */
export type UserActivityStat = {
  /**
   * Email
   */
  email: string;
  /**
   * Full Name
   */
  full_name: string | null;
  /**
   * Count
   */
  count: number;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  role?: UserRole;
  /**
   * Password
   */
  password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  role?: UserRole;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserRole
 */
export type UserRole = "super" | "admin" | "user";

/**
 * UserStats
 */
export type UserStats = {
  /**
   * Total Users
   */
  total_users: number;
  /**
   * Active Users 24H
   */
  active_users_24h: number;
  /**
   * New Registrations 24H
   */
  new_registrations_24h: number;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  role?: UserRole | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type MetricsMetricsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/metrics";
};

export type MetricsMetricsGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type MetricsMetricsGetError =
  MetricsMetricsGetErrors[keyof MetricsMetricsGetErrors];

export type MetricsMetricsGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/checkDBConnection";
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetError =
  CheckDatabaseConnectionApiV1CheckDbConnectionGetErrors[keyof CheckDatabaseConnectionApiV1CheckDbConnectionGetErrors];

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetResponses = {
  /**
   * Response Check Database Connection Api V1 Checkdbconnection Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetResponse =
  CheckDatabaseConnectionApiV1CheckDbConnectionGetResponses[keyof CheckDatabaseConnectionApiV1CheckDbConnectionGetResponses];

export type GetEnvSettingsApiV1GetEnvironmentGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/getEnvironment";
};

export type GetEnvSettingsApiV1GetEnvironmentGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type GetEnvSettingsApiV1GetEnvironmentGetError =
  GetEnvSettingsApiV1GetEnvironmentGetErrors[keyof GetEnvSettingsApiV1GetEnvironmentGetErrors];

export type GetEnvSettingsApiV1GetEnvironmentGetResponses = {
  /**
   * Response Get Env Settings Api V1 Getenvironment Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type GetEnvSettingsApiV1GetEnvironmentGetResponse =
  GetEnvSettingsApiV1GetEnvironmentGetResponses[keyof GetEnvSettingsApiV1GetEnvironmentGetResponses];

export type GetCustomWelcomeMessageApiV1UserNameGetData = {
  body?: never;
  path: {
    /**
     * User Name
     */
    user_name: string;
  };
  query?: never;
  url: "/api/v1/{user_name}";
};

export type GetCustomWelcomeMessageApiV1UserNameGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCustomWelcomeMessageApiV1UserNameGetError =
  GetCustomWelcomeMessageApiV1UserNameGetErrors[keyof GetCustomWelcomeMessageApiV1UserNameGetErrors];

export type GetCustomWelcomeMessageApiV1UserNameGetResponses = {
  /**
   * Response Get Custom Welcome Message Api V1  User Name  Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type GetCustomWelcomeMessageApiV1UserNameGetResponse =
  GetCustomWelcomeMessageApiV1UserNameGetResponses[keyof GetCustomWelcomeMessageApiV1UserNameGetResponses];

export type GetWelcomeMessageApiV1GetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/";
};

export type GetWelcomeMessageApiV1GetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type GetWelcomeMessageApiV1GetError =
  GetWelcomeMessageApiV1GetErrors[keyof GetWelcomeMessageApiV1GetErrors];

export type GetWelcomeMessageApiV1GetResponses = {
  /**
   * Response Get Welcome Message Api V1  Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type GetWelcomeMessageApiV1GetResponse =
  GetWelcomeMessageApiV1GetResponses[keyof GetWelcomeMessageApiV1GetResponses];

export type ReadUsersApiV1UsersGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Size
     *
     * Page size
     */
    size?: number;
  };
  url: "/api/v1/users/";
};

export type ReadUsersApiV1UsersGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadUsersApiV1UsersGetError =
  ReadUsersApiV1UsersGetErrors[keyof ReadUsersApiV1UsersGetErrors];

export type ReadUsersApiV1UsersGetResponses = {
  /**
   * Successful Response
   */
  200: PageUserPublic;
};

export type ReadUsersApiV1UsersGetResponse =
  ReadUsersApiV1UsersGetResponses[keyof ReadUsersApiV1UsersGetResponses];

export type CreateUserApiV1UsersPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/v1/users/";
};

export type CreateUserApiV1UsersPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError =
  CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type CreateUserApiV1UsersPostResponse =
  CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type ReadUserByIdApiV1UsersByIdIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/byID/{id}";
};

export type ReadUserByIdApiV1UsersByIdIdGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadUserByIdApiV1UsersByIdIdGetError =
  ReadUserByIdApiV1UsersByIdIdGetErrors[keyof ReadUserByIdApiV1UsersByIdIdGetErrors];

export type ReadUserByIdApiV1UsersByIdIdGetResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type ReadUserByIdApiV1UsersByIdIdGetResponse =
  ReadUserByIdApiV1UsersByIdIdGetResponses[keyof ReadUserByIdApiV1UsersByIdIdGetResponses];

export type ReadUserByEmailApiV1UsersByEmailEmailGetData = {
  body?: never;
  path: {
    /**
     * Email
     */
    email: string;
  };
  query?: never;
  url: "/api/v1/users/byEmail/{email}";
};

export type ReadUserByEmailApiV1UsersByEmailEmailGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadUserByEmailApiV1UsersByEmailEmailGetError =
  ReadUserByEmailApiV1UsersByEmailEmailGetErrors[keyof ReadUserByEmailApiV1UsersByEmailEmailGetErrors];

export type ReadUserByEmailApiV1UsersByEmailEmailGetResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type ReadUserByEmailApiV1UsersByEmailEmailGetResponse =
  ReadUserByEmailApiV1UsersByEmailEmailGetResponses[keyof ReadUserByEmailApiV1UsersByEmailEmailGetResponses];

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/password-history";
};

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetError =
  ReadPasswordHistoryApiV1UsersMePasswordHistoryGetErrors[keyof ReadPasswordHistoryApiV1UsersMePasswordHistoryGetErrors];

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponses = {
  /**
   * Successful Response
   */
  200: PasswordHistoriesPublic;
};

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponse =
  ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponses[keyof ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponses];

export type UpdatePasswordApiV1UsersPasswordPatchData = {
  body: UpdatePassword;
  path?: never;
  query?: never;
  url: "/api/v1/users/password";
};

export type UpdatePasswordApiV1UsersPasswordPatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePasswordApiV1UsersPasswordPatchError =
  UpdatePasswordApiV1UsersPasswordPatchErrors[keyof UpdatePasswordApiV1UsersPasswordPatchErrors];

export type UpdatePasswordApiV1UsersPasswordPatchResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type UpdatePasswordApiV1UsersPasswordPatchResponse =
  UpdatePasswordApiV1UsersPasswordPatchResponses[keyof UpdatePasswordApiV1UsersPasswordPatchResponses];

export type DeleteUserApiV1UsersIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}";
};

export type DeleteUserApiV1UsersIdDeleteErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteUserApiV1UsersIdDeleteError =
  DeleteUserApiV1UsersIdDeleteErrors[keyof DeleteUserApiV1UsersIdDeleteErrors];

export type DeleteUserApiV1UsersIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type DeleteUserApiV1UsersIdDeleteResponse =
  DeleteUserApiV1UsersIdDeleteResponses[keyof DeleteUserApiV1UsersIdDeleteResponses];

export type UpdateUserApiV1UsersIdPatchData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}";
};

export type UpdateUserApiV1UsersIdPatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserApiV1UsersIdPatchError =
  UpdateUserApiV1UsersIdPatchErrors[keyof UpdateUserApiV1UsersIdPatchErrors];

export type UpdateUserApiV1UsersIdPatchResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type UpdateUserApiV1UsersIdPatchResponse =
  UpdateUserApiV1UsersIdPatchResponses[keyof UpdateUserApiV1UsersIdPatchResponses];

export type ReadTodosApiV1TodosGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/todos/";
};

export type ReadTodosApiV1TodosGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type ReadTodosApiV1TodosGetError =
  ReadTodosApiV1TodosGetErrors[keyof ReadTodosApiV1TodosGetErrors];

export type ReadTodosApiV1TodosGetResponses = {
  /**
   * Successful Response
   */
  200: ToDoListsPublic;
};

export type ReadTodosApiV1TodosGetResponse =
  ReadTodosApiV1TodosGetResponses[keyof ReadTodosApiV1TodosGetResponses];

export type CreateTodoApiV1TodosPostData = {
  body: ToDoListCreate;
  path?: never;
  query?: never;
  url: "/api/v1/todos/";
};

export type CreateTodoApiV1TodosPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTodoApiV1TodosPostError =
  CreateTodoApiV1TodosPostErrors[keyof CreateTodoApiV1TodosPostErrors];

export type CreateTodoApiV1TodosPostResponses = {
  /**
   * Successful Response
   */
  200: ToDoListPublic;
};

export type CreateTodoApiV1TodosPostResponse =
  CreateTodoApiV1TodosPostResponses[keyof CreateTodoApiV1TodosPostResponses];

export type DeleteTodoApiV1TodosIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/todos/{id}";
};

export type DeleteTodoApiV1TodosIdDeleteErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTodoApiV1TodosIdDeleteError =
  DeleteTodoApiV1TodosIdDeleteErrors[keyof DeleteTodoApiV1TodosIdDeleteErrors];

export type DeleteTodoApiV1TodosIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type DeleteTodoApiV1TodosIdDeleteResponse =
  DeleteTodoApiV1TodosIdDeleteResponses[keyof DeleteTodoApiV1TodosIdDeleteResponses];

export type ReadTodoByIdApiV1TodosIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/todos/{id}";
};

export type ReadTodoByIdApiV1TodosIdGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadTodoByIdApiV1TodosIdGetError =
  ReadTodoByIdApiV1TodosIdGetErrors[keyof ReadTodoByIdApiV1TodosIdGetErrors];

export type ReadTodoByIdApiV1TodosIdGetResponses = {
  /**
   * Successful Response
   */
  200: ToDoListPublic;
};

export type ReadTodoByIdApiV1TodosIdGetResponse =
  ReadTodoByIdApiV1TodosIdGetResponses[keyof ReadTodoByIdApiV1TodosIdGetResponses];

export type UpdateTodoApiV1TodosIdPatchData = {
  body: ToDoListUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/todos/{id}";
};

export type UpdateTodoApiV1TodosIdPatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTodoApiV1TodosIdPatchError =
  UpdateTodoApiV1TodosIdPatchErrors[keyof UpdateTodoApiV1TodosIdPatchErrors];

export type UpdateTodoApiV1TodosIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ToDoListPublic;
};

export type UpdateTodoApiV1TodosIdPatchResponse =
  UpdateTodoApiV1TodosIdPatchResponses[keyof UpdateTodoApiV1TodosIdPatchResponses];

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
  body: BodyLoginAccessTokenApiV1LoginAccessTokenPost;
  path?: never;
  query?: never;
  url: "/api/v1/login/access-token";
};

export type LoginAccessTokenApiV1LoginAccessTokenPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostError =
  LoginAccessTokenApiV1LoginAccessTokenPostErrors[keyof LoginAccessTokenApiV1LoginAccessTokenPostErrors];

export type LoginAccessTokenApiV1LoginAccessTokenPostResponses = {
  /**
   * Successful Response
   */
  200: Token;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse =
  LoginAccessTokenApiV1LoginAccessTokenPostResponses[keyof LoginAccessTokenApiV1LoginAccessTokenPostResponses];

export type ReadSecureApiV1LoginSecureDataGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/login/secure-data";
};

export type ReadSecureApiV1LoginSecureDataGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type ReadSecureApiV1LoginSecureDataGetError =
  ReadSecureApiV1LoginSecureDataGetErrors[keyof ReadSecureApiV1LoginSecureDataGetErrors];

export type ReadSecureApiV1LoginSecureDataGetResponses = {
  /**
   * Response Read Secure Api V1 Login Secure Data Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type ReadSecureApiV1LoginSecureDataGetResponse =
  ReadSecureApiV1LoginSecureDataGetResponses[keyof ReadSecureApiV1LoginSecureDataGetResponses];

export type GetCurrentUserApiV1LoginCurrentUserGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/login/current-user";
};

export type GetCurrentUserApiV1LoginCurrentUserGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type GetCurrentUserApiV1LoginCurrentUserGetError =
  GetCurrentUserApiV1LoginCurrentUserGetErrors[keyof GetCurrentUserApiV1LoginCurrentUserGetErrors];

export type GetCurrentUserApiV1LoginCurrentUserGetResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type GetCurrentUserApiV1LoginCurrentUserGetResponse =
  GetCurrentUserApiV1LoginCurrentUserGetResponses[keyof GetCurrentUserApiV1LoginCurrentUserGetResponses];

export type RegisterUserApiV1LoginSignupPostData = {
  body: UserRegister;
  path?: never;
  query?: never;
  url: "/api/v1/login/signup";
};

export type RegisterUserApiV1LoginSignupPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterUserApiV1LoginSignupPostError =
  RegisterUserApiV1LoginSignupPostErrors[keyof RegisterUserApiV1LoginSignupPostErrors];

export type RegisterUserApiV1LoginSignupPostResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type RegisterUserApiV1LoginSignupPostResponse =
  RegisterUserApiV1LoginSignupPostResponses[keyof RegisterUserApiV1LoginSignupPostResponses];

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostData = {
  body?: never;
  path: {
    /**
     * Email
     */
    email: string;
  };
  query?: never;
  url: "/api/v1/login/password-recovery/{email}";
};

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostError =
  RecoverPasswordApiV1LoginPasswordRecoveryEmailPostErrors[keyof RecoverPasswordApiV1LoginPasswordRecoveryEmailPostErrors];

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponse =
  RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponses[keyof RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponses];

export type ReadMyActivitiesApiV1ActivitiesMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/activities/me";
};

export type ReadMyActivitiesApiV1ActivitiesMeGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type ReadMyActivitiesApiV1ActivitiesMeGetError =
  ReadMyActivitiesApiV1ActivitiesMeGetErrors[keyof ReadMyActivitiesApiV1ActivitiesMeGetErrors];

export type ReadMyActivitiesApiV1ActivitiesMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserActivitiesPublic;
};

export type ReadMyActivitiesApiV1ActivitiesMeGetResponse =
  ReadMyActivitiesApiV1ActivitiesMeGetResponses[keyof ReadMyActivitiesApiV1ActivitiesMeGetResponses];

export type ReadAllActivitiesApiV1ActivitiesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Size
     *
     * Page size
     */
    size?: number;
  };
  url: "/api/v1/activities/";
};

export type ReadAllActivitiesApiV1ActivitiesGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadAllActivitiesApiV1ActivitiesGetError =
  ReadAllActivitiesApiV1ActivitiesGetErrors[keyof ReadAllActivitiesApiV1ActivitiesGetErrors];

export type ReadAllActivitiesApiV1ActivitiesGetResponses = {
  /**
   * Successful Response
   */
  200: PageUserActivityPublic;
};

export type ReadAllActivitiesApiV1ActivitiesGetResponse =
  ReadAllActivitiesApiV1ActivitiesGetResponses[keyof ReadAllActivitiesApiV1ActivitiesGetResponses];

export type ReadDashboardStatsApiV1DashboardStatsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/dashboard/stats";
};

export type ReadDashboardStatsApiV1DashboardStatsGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type ReadDashboardStatsApiV1DashboardStatsGetError =
  ReadDashboardStatsApiV1DashboardStatsGetErrors[keyof ReadDashboardStatsApiV1DashboardStatsGetErrors];

export type ReadDashboardStatsApiV1DashboardStatsGetResponses = {
  /**
   * Successful Response
   */
  200: DashboardReport;
};

export type ReadDashboardStatsApiV1DashboardStatsGetResponse =
  ReadDashboardStatsApiV1DashboardStatsGetResponses[keyof ReadDashboardStatsApiV1DashboardStatsGetResponses];

export type ReadAdminDashboardStatsApiV1AdminDashboardStatsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/admin/dashboard/stats";
};

export type ReadAdminDashboardStatsApiV1AdminDashboardStatsGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type ReadAdminDashboardStatsApiV1AdminDashboardStatsGetError =
  ReadAdminDashboardStatsApiV1AdminDashboardStatsGetErrors[keyof ReadAdminDashboardStatsApiV1AdminDashboardStatsGetErrors];

export type ReadAdminDashboardStatsApiV1AdminDashboardStatsGetResponses = {
  /**
   * Successful Response
   */
  200: AdminDashboardReport;
};

export type ReadAdminDashboardStatsApiV1AdminDashboardStatsGetResponse =
  ReadAdminDashboardStatsApiV1AdminDashboardStatsGetResponses[keyof ReadAdminDashboardStatsApiV1AdminDashboardStatsGetResponses];

export type ReadSystemLogsApiV1AdminDashboardLogsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Level
     */
    level?: string | null;
  };
  url: "/api/v1/admin/dashboard/logs";
};

export type ReadSystemLogsApiV1AdminDashboardLogsGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadSystemLogsApiV1AdminDashboardLogsGetError =
  ReadSystemLogsApiV1AdminDashboardLogsGetErrors[keyof ReadSystemLogsApiV1AdminDashboardLogsGetErrors];

export type ReadSystemLogsApiV1AdminDashboardLogsGetResponses = {
  /**
   * Successful Response
   */
  200: SystemLogsPublic;
};

export type ReadSystemLogsApiV1AdminDashboardLogsGetResponse =
  ReadSystemLogsApiV1AdminDashboardLogsGetResponses[keyof ReadSystemLogsApiV1AdminDashboardLogsGetResponses];

export type TriggerErrorApiV1AdminDashboardErrorTestGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/admin/dashboard/error-test";
};

export type TriggerErrorApiV1AdminDashboardErrorTestGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type TriggerErrorApiV1AdminDashboardErrorTestGetError =
  TriggerErrorApiV1AdminDashboardErrorTestGetErrors[keyof TriggerErrorApiV1AdminDashboardErrorTestGetErrors];

export type TriggerErrorApiV1AdminDashboardErrorTestGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type HealthHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthHealthGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
};

export type HealthHealthGetError =
  HealthHealthGetErrors[keyof HealthHealthGetErrors];

export type HealthHealthGetResponses = {
  /**
   * Response Health Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthHealthGetResponse =
  HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type TestEmailTestEmailPostData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Email To
     */
    email_to: string;
  };
  url: "/test-email/";
};

export type TestEmailTestEmailPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorDetail;
  /**
   * Forbidden
   */
  403: ErrorDetail;
  /**
   * Not Found
   */
  404: ErrorDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TestEmailTestEmailPostError =
  TestEmailTestEmailPostErrors[keyof TestEmailTestEmailPostErrors];

export type TestEmailTestEmailPostResponses = {
  /**
   * Successful Response
   */
  201: Message;
};

export type TestEmailTestEmailPostResponse =
  TestEmailTestEmailPostResponses[keyof TestEmailTestEmailPostResponses];
